### ISSUE TITLE
Linux installation is pretty vague.

### ISSUE THREAD

**Issue by xplshn** [devendrn/newb-x-mcbe#3]
Where do I get the new bin files and what is the exact dir for the old ones I've to replace?

**Comment by devendrn** [comment]
Build the shader to get the material.bin files or, download the already built mcpack from github releases/discord server. 

The bin files are inside renderer/materials/ folder of the pack. Extract the .mcpack to get it.

You can then move these files to `mcpelauncher/versions/1.20.x.x/assets/renderer/materials` . Make sure to backup all original material.bin files so that you can restore it later.

**Comment by xplshn** [comment]
thx, will try to install now

**Comment by miqumi** [comment]
> Where do I get the new bin files and what is the exact dir for the old ones I've to replace?

The title is SOOOO misleading goddamn
[literally here](https://github.com/devendrn/newb-x-mcbe#linux-minecraft-manifest)
